# Naming conventions:
#
# fl - front left  | fr - front right
# cl - center left | cr - center right
# rl - rear left   | rr - rear right

# Pin numbers for motors on PWM board
pin_drive_fl: 12
pin_steer_fl: 14

pin_drive_fr: 1
pin_steer_fr: 0

pin_drive_cl: 13
pin_steer_cl: 15

pin_drive_cr: 3
pin_steer_cr: 2

pin_drive_rl: 7
pin_steer_rl: 6

pin_drive_rr: 5
pin_steer_rr: 4

## PWM values
# Those values highly depend on the motors and pwm board used
# Check out the wiki for further explanation

# PWM values for the neutral steering position
steer_pwm_neutral_fl: 325
steer_pwm_neutral_fr: 320
steer_pwm_neutral_cl: 315
steer_pwm_neutral_cr: 330
steer_pwm_neutral_rl: 325
steer_pwm_neutral_rr: 335

# PWW range around steering neutral position
steer_pwm_range: 250

# PWM value for the stop position of driving motors
drive_pwm_neutral: 307

# PWW range around driving neutral position
drive_pwm_range: 100
